### ISSUE TITLE
Sub-directory exclusion while generating hash for directory

### ISSUE THREAD

**Issue by peanutpi** [mac-/hash-files#2]
I have to generate hash for a directory with some of the sub-directory or files are excluded

For e.g. There is a directory

/path/to/dir/abc/

This Directory has following sub directories & file

- `foo` 
- `bar` 
- `secrets.txt`

I don't want to include bar directory while creating hash for directory 'abc'

So, please provide a way we can exclude directory or file while generating hash of a directory.

ps:: we can use [`glob-all`](https://www.npmjs.com/package/glob-all) instead of `glob` to get the path of the directory.

**Comment by peanutpi** [comment]
#3

**Comment by peanutpi** [comment]
https://github.com/mac-/hash-files/pull/3

**Comment by mac-** [comment]
Thanks. The fix for this has been published as v1.1.1.
